-- SELECT 'INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES ('||globalmacroid||', '''||REPLACE(macro, '''', '''''')||''', '''||REPLACE(value, '''', '''''')||''', '''||REPLACE(description, '''', '''''')||''', '||type||');' AS sql FROM globalmacro ORDER BY globalmacroid;
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (2, '{$SNMP_COMMUNITY}', 'public', '', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (3, '{$OFFICE_HOURS_BEGIN}', '090000', 'HHMMSS office-hours start', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (4, '{$OFFICE_HOURS_END}', '180000', 'HHMMSS office-hours end', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (5, '{$HAS_DISASTER}', '1', '1=disaster, 0=no_disaster, 9to5=office-hours-disaster', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (6, '{$ENABLE_CPU_COUNT_TRIGGER}', '0', '0 = disabled, 1 = enabled, Triggers if {$CPU_COUNT_WANTED} does not match the CPU count', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (7, '{$ENABLE_RAM_COUNT_TRIGGER}', '0', '0 = disabled, 1 = enabled, Triggers if {$RAM_COUNT_WANTED} does not match the RAM count', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (8, '{$CPU_COUNT_WANTED}', '1', '1 CPU. Number of CPU''s wanted, override via templates or host macro''s', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (9, '{$RAM_COUNT_WANTED}', '2147483648', '2GB. Total RAM of machine, override via templates or host macro''s', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (10, '{$CERT_EXPIRY_HIGH}', '14', 'If certificates are valid less days, generate high trigger', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (11, '{$CERT_EXPIRY_CRIT}', '5', 'If certificates are valid less days, generate critical trigger', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (12, '{$ZFS_SPACE_BELOW_DISASTER}', '12', 'Disaster alert when disk free% reaches below', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (13, '{$ZFS_SPACE_BELOW_HIGH}', '20', 'High alert when disk free% reaches below', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (14, '{$DISKIO_MOUNT_FREE_BELOW_DISASTER}', '10', 'Disaster alert when disk free% reaches below', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (15, '{$DISKIO_MOUNT_FREE_BELOW_HIGH}', '20', 'High alert when disk free% reaches below', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (16, '{$DISK_LEFT_CRIT}', '10', 'Percentage of disk space left free before a critical gets send (XXX OLD? used in Template Debian-ish -> Mounted filesystem discovery)', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (17, '{$DISABLE_IOWAIT}', '0', 'Set to 1 to disable IO Wait triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (18, '{$TIMEZONE}', 'Europe/Amsterdam', 'expected timezone', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (19, '{$DISABLE_CPU_LOAD}', '0', 'Set to 1 to disable CPU load triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (20, '{$DISABLE_MEMORY}', '0', 'Set to 1 to disable lack of available memory triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (21, '{$DISABLE_OOM}', '0', 'Set  to 1 to disable recent oomkill detected triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (22, '{$TEMPLATE_OS_DEBIANISH}', '0', 'Used to check if we have the Template OS Debian''ish assigned to a host', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (23, '{$HAS_TEMPLATE_ZFS}', '0', 'Used to check if we have the Template ZFS assigned to a host', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (24, '{$JOURNALD_DISK}', '1', 'require journald logs on disk vs. require them in memory only', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (25, '{$LIMIT_MEM_FREE_HIGH}', '2', 'High trigger when less than 2% free memory', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (26, '{$LIMIT_MEM_FREE}', '10', 'Informational trigger when less 10% free memory', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (27, '{$MIN_MEMORY_BYTES_FREE}', '6442450944', 'Minimum bytes of memory that needs to be available', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (28, '{$LIMIT_PROC_NUM}', '750', 'Amount of processes should not exceed this value', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (29, '{$DAEMON_PROCMEM_PROCESSES}', '', 'put "nats-server processx processy" here', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (30, '{$DISABLE_GOCOLLECT}', '0', 'Set to 1 to disable gocollect triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (31, '{$DISABLE_JOURNALD}', '0', 'Set to 1 to disable journald triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (32, '{$DISABLE_LOCALMAIL}', '0', 'Set to 1 to disable local mail triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (33, '{$DISABLE_NEEDSRESTART}', '0', 'Set to 1 to disable "processes require restart" triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (34, '{$DISABLE_NEEDSUPDATES}', '0', 'Set to 1 to disable update notification triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (35, '{$DISABLE_NTP}', '0', 'Set to 1 to disable ntp triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (36, '{$DISABLE_PSDIFF}', '0', 'Set to 1 to disable psdiff triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (37, '{$DISABLE_RSYSLOG}', '0', 'Set to 1 to disable rsyslog triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (38, '{$MAIL_QUEUE_CRITICAL}', '1000', 'Amount of mail allowed to pile up in the queue before it generates a critical trigger', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (39, '{$MAIL_QUEUE_HIGH}', '750', 'Amount of mail allowed to pile up in the queue before it generates a high trigger', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (40, '{$MAX_FILES_PROMILLE_HIGH}', '800', 'Amount of open files allowed by a single process before a high trigger is generated', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (41, '{$MAX_FILES_PROMILLE_WARN}', '600', 'Amount of open files allowed by a single process before a warning trigger is generated', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (42, '{$DISABLE_ZBXNOHW}', '0', 'Set to 1 to disable the "Needs hardware template" for hardware machines (or wrongly detected virtual machines)', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (43, '{$DISABLE_FIREWALL}', '0', 'Set to 1 to disable firewall triggers', 0);
INSERT INTO regexps (globalmacroid, macro, value, description, type) VALUES (44, '{$KERNEL_SLABPCT}', '20', 'Expect less than N% kernel slab usage (increase on ZFS systems)', 0);
