#!/usr/bin/env python3
# [This file is part of the zabbix-agent-osso package]
from k8s_zabbix_base import K8sZabbixBase


class RabbitMQMonitor(K8sZabbixBase):
    def __init__(self):
        super().__init__(
            name='k8s-rabbitmq',
            description='RabbitMQ Zabbix monitoring',
            label='ossobv/zabbix-agent-osso.k8s-rabbitmq=true',
            cm_prefix='status-rabbitmq',
        )

    def is_valid_node(self, node_value: str) -> bool:
        return node_value.startswith('{"status')


if __name__ == '__main__':
    RabbitMQMonitor().run()
