#!/bin/sh
# [This file is part of the zabbix-agent-osso package]
# REQUIRES: jq, kubectl
#

get_contexts() {
    kubectl config get-contexts -oname
}

make_json() {
    echo '{"{#CONTEXT}":"'$1'","{#NAMESPACE}":"'$2'","{#STARTSWITH}":"'$3'"}'
}

get_namespace_info() {
    for context in $(get_contexts); do
        kubectl --context "$context" get namespace -o json \
        | jq -r --arg context "$context" '
            .items[]
            | {
                namespace: .metadata.name,
                startswith: (
                    .metadata.annotations[
                        "ossobv/zabbix-agent-osso.k8s-pods-ready"]
                    | select(. != null)
                    | fromjson
                    | if has("startswith") then .startswith[] else "ANY" end
                )
            }
            | [$context, .namespace, .startswith] | join("|")
        '
    done
}

if [ "$1" = "discover" ]; then
    get_namespace_info | while IFS="|" read -r context ns startswith; do
        make_json "$context" "$ns" "$startswith"
    done | jq -sc
    exit 0

elif [ "$1" = "values" ]; then
    # First, check whether this is something for us.
    expected_match="${2}|${3}|${4}"

    if ! get_namespace_info | grep -Fxq "$expected_match"; then
        # FIXME: What do we do if the namespace is not matched anymore?
        # Does that mean it is gone and everything has to Panic?
        # Or does it mean that we disabled the ready check because we're doing
        # maint, or are done with this trigger?
        # Right now, we'll go with "maint".
        echo '{"all_ready": true, "warning": "not_found"}'
        exit 0
    fi

    if [ "$4" = "ANY" ]; then
        startswith=
    else
        startswith=$4
    fi

    # For now, eat errors so they turn into all_ready=false.
    bool=$(kubectl --context "$2" get pods -n "$3" -ojson 2>&1 |
        jq -r '[.items[] | select(.metadata.name | startswith("'"$startswith"'")) |
        .status.containerStatuses[] | .ready==true] | all' 2>&1)
    # This is a temporary output which we may improve on later on. By starting
    # out with a json object, we can more easily expand on it with other
    # values.
    if [ "$bool" = true ]; then
        echo '{"all_ready": true}'
    else
        echo '{"all_ready": false}'
    fi
    exit 0

else
    echo "possible actions:
    discover
    values context namespace startswith" 2>&1
    exit 1
fi
