#!/bin/sh
# [This file is part of the zabbix-agent-osso package]
# REQUIRES: kubectl, jq
#

get_contexts() {
    kubectl config get-contexts -oname
}

get_namespaces() {
    kubectl get namespace -l ossobv/zabbix-agent-osso.k8s-pods-ready=true \
            --context "$1" -oname 2>/dev/null |
        sed -e 's/namespace\///'
}

if [ "$1" = "--discover" ]; then
    for context in $(get_contexts); do
        for namespace in $(get_namespaces "$context"); do
            startswith=$(kubectl --context $context get namespace $namespace \
                -ojsonpath='{.metadata.labels}' |
                jq -r '."ossobv/zabbix-agent-osso.k8s-pods-ready-startswith"')
            echo '{"{#CONTEXT}":"'$context'","{#NAMESPACE}":"'$namespace'",'"\
                "'"{#STARTSWITH}":"'$startswith'"}'
        done
    done | jq -sc
    exit 0

elif [ "$1" = "--get-values" ]; then
    kubectl --context $2 get pods -n $3 -ojson |
        jq -r '[.items[] | select(.metadata.name | startswith("'"$4"'")) |
            .status.containerStatuses[] | .ready==true] | all '
    exit 0

else
    echo "possible options:
    --discover
    --get-values $context $namespace $startswith"
    exit 1
fi

