#!/usr/bin/env python3
# [This file is part of the zabbix-agent-osso package]
from k8s_zabbix_base import K8sZabbixBase


class GaleraMonitor(K8sZabbixBase):
    def __init__(self):
        super().__init__(
            name='k8s-galera',
            description='K8s-galera Zabbix monitoring',
            label='ossobv/zabbix-agent-osso.k8s-galera=true',
            cm_prefix='status-galera',
        )

    def is_valid_node(self, node_value: str) -> bool:
        return 'wsrep' in node_value


if __name__ == '__main__':
    GaleraMonitor().run()
