#!/bin/sh -e
# [This file is part of the zabbix-agent-osso package]
# Very thin wrapper around mysql/mysqladmin for instance support, keeping
# compatibility with the original zabbix-agent-osso .my.cnf file.

# Reduce execve()ing of all /sbin/ dirs. But keep the option open of having a
# customized version in /usr/local/bin.
PATH=/usr/local/bin:/usr/bin:/bin

bin=${1:-is-alive}; shift

get_cnf() {
    cnf=/etc/zabbix/config/mysql.$1.cnf
    if ! test -s "$cnf"; then
        if test "$1" = default && test -s /etc/zabbix/mysql/.my.cnf; then
            cnf=/etc/zabbix/mysql/.my.cnf
        else
            echo "ZBX_ERROR: missing instance $1 cnf" >&2
            exit 1
        fi
    fi
}

if test "$bin" = cli; then
    get_cnf "${1:-default}"; shift
    exec mysql --defaults-file="$cnf" "$@"
elif test "$bin" = "is-alive"; then
    get_cnf "${1:-default}"; shift
    ret=$(timeout 2s mysqladmin --defaults-file="$cnf" ping 2>/dev/null)
    test "$ret" = "mysqld is alive" && echo 1 || echo 0
    exit 0
elif test "$bin" = discover_instances; then
    echo "["
    notfirst=
    for cnf in /etc/zabbix/config/mysql.*.cnf; do
        if test -s "$cnf"; then
            instance=${cnf##*/mysql.}; instance=${instance%.cnf}
            test -n "$notfirst" && echo -n ,; notfirst=1
            echo "{\"{#INSTANCE}\": \"$instance\"}"
        fi
    done
    test -z "$notfirst" && test -s /etc/zabbix/mysql/.my.cnf &&
        echo "{\"{#INSTANCE}\": \"default\"}"
    echo "]"
elif test "$bin" = no-v2-conf; then
    for cnf in /etc/zabbix/config/mysql.*.cnf; do
        test -s "$cnf" && exit 1
    done
    exit 0
else
    echo "mysql: UNKNOWN: $bin: $@" >&2
    exit 1
fi
