#!/bin/sh -e
# [This file is part of the zabbix-agent-osso package]
# Very thin wrapper around mysql/mysqladmin for instance support, keeping
# compatibility with the original zabbix-agent-osso .my.cnf file.

# Reduce execve()ing of all /sbin/ dirs. But keep the option open of having a
# customized version in /usr/local/bin.
PATH=/usr/local/bin:/usr/bin:/bin

bin=${1:-is-alive}; shift

get_cnf() {
    if test -s "/etc/zabbix/config/mysql2.$1.cnf"; then
        cnf=/etc/zabbix/config/mysql2.$1.cnf
    elif test -s "/etc/zabbix/config/mysql.$1.cnf"; then
        cnf=/etc/zabbix/config/mysql.$1.cnf
    elif test "$1" = default && test -s /etc/zabbix/mysql/.my.cnf; then
        cnf=/etc/zabbix/mysql/.my.cnf
    else
        echo "ZBX_ERROR: missing instance $1 cnf" >&2
        exit 1
    fi
}

if test "$bin" = cli; then
    get_cnf "${1:-default}"; shift
    exec mysql --defaults-file="$cnf" "$@"
elif test "$bin" = "is-alive"; then
    get_cnf "${1:-default}"; shift
    ret=$(timeout 2s mysqladmin --defaults-file="$cnf" ping 2>/dev/null)
    test "$ret" = "mysqld is alive" && echo 1 || echo 0
    exit 0
elif test "$bin" = discover_instances; then
    echo "["
    notfirst=
    for cnf in /etc/zabbix/config/mysql2.*.cnf \
               /etc/zabbix/config/mysql.*.cnf; do
        if test -s "$cnf"; then
            # Set: [zabbix] severity=5 for DISASTER, severity=4 for HIGH
            severity=$(sed -e '
                1,/^[[]zabbix[]]/d
                /^[[]/,$d
                /^severity=/!d
                s/^[^=]*=//
            ' "$cnf")
            test -n "$severity" || severity=5

            if test "${cnf##*/mysql2.}" != "$cnf"; then
                instance=${cnf##*/mysql2.}
            else
                instance=${cnf##*/mysql.}
            fi
            instance=${instance%.cnf}
            test -n "$notfirst" && echo -n ,; notfirst=1
            echo "{\"{#INSTANCE}\": \"$instance\",\
\"{#SEVERITY}\": $severity}"
        fi
    done
    test -z "$notfirst" && test -s /etc/zabbix/mysql/.my.cnf &&
        echo "{\"{#INSTANCE}\": \"default\", \"{#SEVERITY}\": 5}"
    echo "]"
elif test "$bin" = no-v2-conf; then
    for cnf in /etc/zabbix/config/mysql2.*.cnf \
               /etc/zabbix/config/mysql.*.cnf; do
        test -e "$cnf" && echo ZBX_NOTSUPPORTED >&2 && exit 1
    done
    exit 0
else
    echo "mysql: UNKNOWN: $bin: $@" >&2
    exit 1
fi
