#!/bin/sh
# [This file is part of the zabbix-agent-osso package]
# REQUIRES: awk
#
# Only relevant for Proxmox/PVE systems.
set -eu

export LC_ALL=C

case ${1:-} in
memory)
    # Needs sudo to read /etc/pve/qemu-server/*.conf
    awk -vT="$(free -g)" '
        /^memory:/{s+=$2}
        END{sub("^(.*\n)?Mem:[[:blank:]]*","",T);sub("[[:blank:]].*","",T);
          t=int(T);s=s/1024;
          print "{\"mem_g\":"t",\"vm_g\":"s",\"pct\":"(s*100/t)"}"}
    ' /etc/pve/qemu-server/*.conf 2>/dev/null ||
        echo '{"mem_g":0,"vm_g":0:"pct":0}'
    exit 0
    ;;
*)
    echo "Usage: $0 <memory>" >&2
    exit 1
    ;;
esac
