# [This file is part of the zabbix-agent-osso package]
#
# DEPENDS: jq, kubectl
# SCRIPTS: k8s-galera
#
UserParameter=k8s.galera.discover_instances, sudo /etc/zabbix/scripts/k8s-galera discover-instances
UserParameter=k8s.galera.data[*], sudo /etc/zabbix/scripts/k8s-galera get-data --context "$1" --namespace "$2" --cm "$3" --node "$4"
